### ISSUE TITLE
Develop the login implementation

### ISSUE THREAD

**Issue by joucogi** [joucogi/karumi-code-test#6]
## Task to do

- [x] Develop the login implementation. In this step just validate users saved in a variable.
- [x] Develop a Middleware o Guard to protect the private Home View.
- [x] Home View button will log out and redirect to Login View when it is clicked.
